name: waterreminder
description: Water reminder App.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  share: ^2.0.4
  animations: ^2.0.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  provider: "^6.0.1"
  intl: ^0.17.0
  sqflite: ^2.2.2
  auto_size_text: ^3.0.0
  path: ^1.7.0
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.0
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^1.1.6
  line_awesome_icons: ^1.0.4+2
  flutter_rating_bar: ^4.0.1
  line_awesome_flutter: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: AppSymbols
      fonts:
      - asset: fonts/AppSymbols.ttf

    - family: Comfortaa
      fonts:
      - asset: fonts/Comfortaa-Regular.ttf

      - asset: fonts/Comfortaa-Light.ttf
        weight: 300
      
      - asset: fonts/Comfortaa-Medium.ttf
        weight: 500

      - asset: fonts/Comfortaa-SemiBold.ttf
        weight: 600
      
      - asset: fonts/Comfortaa-Bold.ttf
        weight: 700
    - family: Comfortaa
      fonts:
      - asset: fonts/Comfortaa-Regular.ttf
      - asset: fonts/Comfortaa-Light.ttf
        weight: 300
      - asset: fonts/Comfortaa-Medium.ttf
        weight: 500
      - asset: fonts/Comfortaa-SemiBold.ttf
        weight: 600
      - asset: fonts/Comfortaa-Bold.ttf
        weight: 700

